### ISSUE TITLE
question about restrictred file permissions

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse-ansible#21]
Not sure if this should be posted here or at the dataverse section.

I have a test site at: <http://ec2-54-219-54-246.us-west-1.compute.amazonaws.com:8080/>. I'm trying out restricted file settings.   As a non-admin user I request access, email generated to the admin account includes the link to the Restricted File Permissions page.  From the link I get a 404 file (permissions-manage-files.xhtml  not found) but in the admin account I can navigate to the permissions page from my notifications.  

Obviously I've configured something wrong. I'm going through the documentation but haven't found a solution yet.

**Comment by pdurbin** [comment]
@jmjamison this sounds like a bug to me. You should open bug reports at https://github.com/IQSS/dataverse/issues . But you're concerned that your installation is misconfigured? https://demo.dataverse.org is running 4.9.1 rather than the version you're testing (4.9.2) but can you please try to replicate the bug on that demo server? Thanks!

**Comment by jmjamison** [comment]
I'm trying to replicate on the test server.  Will also open the bug report.
